import type { Metadata } from "next";
import { AcceptInvite } from "./accept-invite";

export const metadata: Metadata = { title: "Accept your invitation" };

// Where an invitation link lands.
//
// It cannot reuse /reset/confirm, and the reason is worth writing down. That
// route reads a ?code= parameter, which is what the forgotten password flow
// produces because the browser starts it and holds the matching verifier. An
// invitation is generated by an admin on the server, so there is no verifier,
// and Supabase hands the session back in the URL fragment instead:
// #access_token=...&refresh_token=... . A fragment is never sent to a server,
// so no server route can read one. This page therefore has to be a client
// page, and the exchange has to happen in the browser.
export default function AcceptInvitePage() {
  return (
    <main className="flex min-h-screen items-center justify-center bg-canvas px-4">
      <div className="w-full max-w-sm">
        <div className="mb-8 flex flex-col items-center gap-3">
          <div className="flex size-10 items-center justify-center rounded-xl bg-primary text-body font-semibold text-primary-foreground">
            W
          </div>
          <div className="text-center">
            <h1 className="text-h2 font-semibold tracking-tight text-text-1">
              Welcome to Work OS
            </h1>
            <p className="page-subtitle mt-1">
              One moment while we check your invitation.
            </p>
          </div>
        </div>
        <AcceptInvite />
      </div>
    </main>
  );
}
